version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5433:5432" # Changed port to 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
